// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachFrontend() {
  return window['go']['backend']['API']['AttachFrontend']();
}

export function DetachFrontend(arg1) {
  return window['go']['backend']['API']['DetachFrontend'](arg1);
}

export function GetAppInfo() {
  return window['go']['backend']['API']['GetAppInfo']();
}

export function GetChanges(arg1) {
  return window['go']['backend']['API']['GetChanges'](arg1);
}

export function GetDiff(arg1) {
  return window['go']['backend']['API']['GetDiff'](arg1);
}

export function GetSessionStatus(arg1) {
  return window['go']['backend']['API']['GetSessionStatus'](arg1);
}

export function Heartbeat(arg1) {
  return window['go']['backend']['API']['Heartbeat'](arg1);
}

export function PauseSession(arg1) {
  return window['go']['backend']['API']['PauseSession'](arg1);
}

export function ResetBaseline(arg1) {
  return window['go']['backend']['API']['ResetBaseline'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['backend']['API']['ResumeSession'](arg1);
}

export function StartSession(arg1) {
  return window['go']['backend']['API']['StartSession'](arg1);
}

export function StopSession(arg1) {
  return window['go']['backend']['API']['StopSession'](arg1);
}
