// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function AttachFrontend():Promise<backend.ConnectionReply>;

export function DetachFrontend(arg1:string):Promise<backend.Reply>;

export function GetAppInfo():Promise<backend.AppInfo>;

export function GetChanges(arg1:backend.ChangesRequest):Promise<backend.ChangesReply>;

export function GetDiff(arg1:backend.DiffRequest):Promise<backend.DiffReply>;

export function GetSessionStatus(arg1:string):Promise<backend.Reply>;

export function Heartbeat(arg1:string):Promise<backend.Reply>;

export function PauseSession(arg1:backend.SessionRequest):Promise<backend.Reply>;

export function ResetBaseline(arg1:backend.SessionRequest):Promise<backend.Reply>;

export function ResumeSession(arg1:backend.SessionRequest):Promise<backend.Reply>;

export function SelectFolder():Promise<backend.FolderReply>;

export function StartSession(arg1:backend.StartOptions):Promise<backend.Reply>;

export function StopSession(arg1:backend.SessionRequest):Promise<backend.Reply>;
